### ISSUE TITLE
Task List core functionality

### ISSUE THREAD

**Issue by RamtinTJB** [cse110-sp24-group12/cse110-sp24-group12#46]
# Overview
Implement the core functionality of the task list widget (you can reuse some code from the warmup exercise but if you do make sure to clean the code up a bit since it was really messy)

## Frontend (UI/UX)
- Task List component with the following functionalities:
  - Each task has: title, checked or not, priority (critical, high, medium, low, ...), a label/tag to indicate which project or context it belongs to
  - User can check/uncheck, add, edit, and delete tasks
  - Apply some basic styling (the actual design is TBD so don't worry too much about this)

## Backend (CRUD operations)
The data for this could be a hardcoded json for now until we decide how we want to implement data storage

## Acceptance Criteria
- [x] Task list widget as specified above
- [x] basic styling (in `styles/task-list.css`)
- [ ] Proper documentation of the functions
- [ ] Unit testing and E2E testing if applicable
