### ISSUE TITLE
Integrating Task List with storage

### ISSUE THREAD

**Issue by RamtinTJB** [cse110-sp24-group12/cse110-sp24-group12#74]
# Overview
Instead of using localStorage, use the functions defined in `main.js` to access entries and tasks. If an entry is a task list, it will be have "tasklist" as "type:

```json
{
        "id": "2",
        "date": "2024-05-24",
        "fileName": "data/tasklist1.json",
        "title": "Random Task List",
        "type": "tasklist",
        "bookmarked": false
}
```

To get an entry by id in any of the javascript files you can call (if the id is 2):

```js
const entry = await window.api.getEntryById('2')
```

And then you can call

```js
const taskItems = await window.api.readFile(entry.fileName)
```

to read the content of the json containing the task list.

## Frontend (UI/UX)
Verify that everything still works with the new integrations

## Backend (CRUD operations)
Replace the localStorage stuff with the filesystem functions defined in `main.js` and `preload.js`

## Acceptance Criteria
- [ ] Remove all the local storage stuff
- [ ] Integrate file system function calls
- [ ] Verify that everything works the same as before
